### ISSUE TITLE
link on interact not working

### ISSUE THREAD

**Issue by goinsidevr** [vrlandio/community#238] opened 2021-11-15 12:34 UTC
can's save any link for "link on interact". I also can't "copy from clipboard".

**Comment by arpu** [comment] 2021-11-15 12:47
cannot reproduce this test on https://vrland.io/nYxTDk/tender_c-3po

does this only happen on the tilt brush model?

**Comment by goinsidevr** [comment] 2021-11-15 12:52
no it also happens with images

**Comment by arpu** [comment] 2021-11-15 12:56
still cannot reproduce this tested on new uploaded image in https://vrland.io/nYxTDk/tender_c-3po 

any error message in the chrome console?

**Comment by goinsidevr** [comment] 2021-11-15 13:03
maybe I need a tutorial then how to do this properly because for my room it doesn't work
I can't copy my link and type it in manually - then I hit enter - when I reload the page no link is connected to the image and no link is shown.

**Comment by arpu** [comment] 2021-11-16 18:28
should be fixed with v0.25.10 plz reopen with you still have a problem

**Comment by goinsidevr** [comment] 2021-11-16 20:58
typing in the link manually works now but I still can't copy and paste.

**Comment by arpu** [comment] 2021-11-16 23:23
you need to press the button next to the field to paste

**Comment by goinsidevr** [comment] 2021-11-17 15:38
I found out about that myself thx (; but this isn't working for me. I know that it did in the past though

**Comment by goinsidevr** [comment] 2021-11-17 15:48
btw I can't re-open issues you closed

**Comment by arpu** [comment] 2021-11-17 15:53
does it work on the other input fields like the username?

**Comment by arpu** [comment] 2021-11-17 15:54
if you press the paste button does the text shown in the input field?

**Comment by goinsidevr** [comment] 2021-11-17 16:03
> 
> 
> does it work on the other input fields like the username?

no, that doesn't work either

**Comment by goinsidevr** [comment] 2021-11-17 16:03
> 
> 
> if you press the paste button does the text shown in the input field?

no, pressing the button doesn't seem to have any impact

**Comment by arpu** [comment] 2021-11-17 16:10
you are on mac? with chrome right?

**Comment by goinsidevr** [comment] 2021-11-17 16:17
no I'm doing this on windows right now. but it's firefox. perhaps I should try chrome...

**Comment by goinsidevr** [comment] 2021-11-17 16:32
okay, I tried with brave browser now. when I click on the paste icon brave asks me if I'd like to give vrland permission to access clipboard. afterward allowing it it works just fine! Juhuu.
firefox though is not asking and I can't recognize any past decision made except HMD and MIC

**Comment by arpu** [comment] 2021-11-17 16:45
its a other problem FF does not support the clipboard API today ( needs some workaround or wit for proper browser support) 
https://web.dev/async-clipboard/

**Comment by arpu** [comment] 2021-11-17 18:41
with v0.25.14 you can paste with strg+v in the inputfield the paste Buttons will be removed

**Closed by arpu** 2021-11-17 18:41 UTC
